### ISSUE TITLE
Change table-title for the sub categories

### ISSUE THREAD

**Issue by ghost** [SStalker/EVOS#108]

**Comment by lhannigbrinck** [comment]
Edited because: Tabel title as it is now is useless, beacuase "Title" as it says now is not saying what is displayed in the tabel. Probably better is: "Unterkategorien" or something else more pointing out what is displayed

**Comment by apollo7321** [comment]
Wir könnten es in ein eigenes div vom Typ panel packen, mit "Unterkategorien" als Überschrift.

**Comment by lhannigbrinck** [comment]
Wäre auch eine möglichkeit, das würde das ganze auch optisch noch weiter voneinander trennen.
