### ISSUE TITLE
Prevent of starting the quiz twice

### ISSUE THREAD

**Issue by lhannigbrinck** [SStalker/EVOS#116]
While a quiz is already started it should not be able to start over again at the same time.

**Comment by SStalker** [comment]
Would it be enough if i change the button to "Quiz beenden" when the quiz is active with route QuizController@beenden to notify the user? Additionally we could deactivate a quiz if it exceed a max active time i.e. 1:30h 

`(Carbon::now()->timestamp - $quizzes->updated_at->timestamp) > 5400`

**Comment by lhannigbrinck** [comment]
This could be an acceptable solution. I think this issue and #109 are pretty much the same.

**Comment by apollo7321** [comment]
Wie willst du so einen Timer implementieren? Ich würde den Button einfach ausblenden, da man ein Quiz eigentlich nicht beenden kann ohne dass der Nutzer informiert wird, oder?

Ich habe gerade eine Methode implementiert, die den Dozenten informiert, wenn ein Attendee die Session schließt. Da könnte man noch einen Check einbauen, dass wenn die Session dem Dozenten gehört, diese prüft ob er ein aktives Quiz hat und die Teilnehmer informiert oder so.

**Comment by lhannigbrinck** [comment]
Ausblenden ist eh noch so eine sache. 
Wurde heute angesprochen un für nicht so toll empfunden, besser wäre da wieder ausgrauen und disablen denke ich.

Ich denke das abbrechen eines quizes könnte man ganz gut in #109 abfangen. Anderersesits sollte das Quiz bei Abbruch durch Disconnect oder dergleichen auch wieder freigegeben werden.

**Comment by apollo7321** [comment]
OK, disable wäre auch in Ordnung. OK, beenden wäre ja nun auch nicht so schlimm, aber das müsste man halte implementieren. Irgendwie überflüssig, oder?

**Comment by lhannigbrinck** [comment]
Beenden, hmmm aber das ist doch schon einmal implementiert, wobei man dann noch einen end befehl an den sync server schicken müsste.

**Comment by apollo7321** [comment]
Ach so, na gut. :) Dann habe ich nichts gesagt.

**Comment by lhannigbrinck** [comment]
Oder habe ich das falsch verstanden, @SStalker ?
