### ISSUE TITLE
Should we set a maximum deep for sub categories?

### ISSUE THREAD

**Issue by lhannigbrinck** [SStalker/EVOS#117]
@SStalker , @cwansart , @lkschenk , @DaHerzog : Should it be possible to create infinit sub-categories, or should it only be possible to a defined depth e.g. 3?

**Comment by apollo7321** [comment]
Nein, ich sehe keinen Grund da drin. Der Nutzer kann ja selbst entscheiden, wie er oder sie strukturiert.
