### ISSUE TITLE
Display owner in category or sub-category tables? 

### ISSUE THREAD

**Issue by lhannigbrinck** [SStalker/EVOS#118]
@SStalker , @cwansart , @lkschenk , @DaHerzog : When the categories or sub-categories are displayed to the user now there is also displayed the owner as "Besitzer". Since we can only show an user his own categories, is there a need to display the owner?

**Comment by SStalker** [comment]
If we can share categories (in future) between users yes.. else no

**Comment by lhannigbrinck** [comment]
If we can share whole categories, we should probably rename the owner as "Besitzer" to creator as "Ersteller" or something like that.

**Comment by apollo7321** [comment]
Vorgesehen ist nur das Teilen eines Quiz. Aber selbst da wird das Quiz kopiert und von der Kopie ist der neue Nutzer natürlich der Besitzer. Eigentlich bräuchten wir den Besitzer gar nicht anzeigen lassen.

**Comment by lhannigbrinck** [comment]
Naja beim teilen des Quiz wäre es schon sinnvoll den anzuzeigen, der das erstellt hat, damit man bei etwaigen rückfragen einen ansprechartner hat.

**Comment by apollo7321** [comment]
Das Problem ist, dass wir diese Info nicht speichern. Das ist nun einfach die Beziehung zwischen Quiz und User.

**Comment by apollo7321** [comment]
Ich denke, das hat sich geklärt. Ich schließe das mal. Wenn es sinnvoll erscheint, bitte wieder öffnen.
