### ISSUE TITLE
Funktion zum Rendern der MathJax Formeln austauschen

### ISSUE THREAD

**Issue by hrzg88** [SStalker/EVOS#148]
Bin beim Bearbeiten der "Warteseite" auf folgendes gestoßen:

http://docs.mathjax.org/en/latest/advanced/typeset.html#typeset-math

Dort steht im zeiten Absatz, dass die Funktion "MathJax.Hub.Typeset()" nie direkt aufgerufen werden soll, sondern stattdessen die Funktion "MathJax.Hub.Queue(["Typeset",MathJax.Hub])". Hintergrund ist die Asynchronität mit der MathJax arbeitet. Wir müssen mal schauen an welchem Stellen die Funktion aufgerufen wird, und es anschließend ändern.

**Comment by lhannigbrinck** [comment]
Da wir bisher immer nur eine Formel pro Seite rendern (es gibt so weit ich weiß keine Seite auf der das mehrfach pro Client aufgerufen wird) ist das zwar nicht zwingen notwendig. Allerings denke ich das wir das schon einbauen sollten, da das Projekt ja evtl weitergeführt wird!

**Comment by apollo7321** [comment]
Hört sich gut an.

**Comment by lhannigbrinck** [comment]
Da wir uns dazu entschieden haben die aktuelle Handhabe beizubehlaten, sollten wir diesen Punkt auf jedenfall in die Dokumentation mit aufnehmen, was sagst du @lkschenk ?

**Comment by ghost** [comment]
Denke ich auch. Fällt wohl unter den Part "Methodendokumentation" oder?

**Comment by lhannigbrinck** [comment]
Ja ich denke schon.
