### ISSUE TITLE
Use background color in question.show

### ISSUE THREAD

**Issue by apollo7321** [SStalker/EVOS#40]
Use background color green for correct and red for false answers.

**Comment by ghost** [comment]
http://getbootstrap.com/css/#helper-classes-backgrounds

**Comment by apollo7321** [comment]
Closed. Thanks to @lkschenk for implementing the correct answers. I had to port the to this branch.
https://github.com/SStalker/EVOS/commit/d80ce46054ba4ebc9f2dcf144f156eac3bba5932
