### ISSUE TITLE
Add css

### ISSUE THREAD

**Issue by apollo7321** [SStalker/EVOS#55]
Could you please add some css for me? I placed it inside a view in `<style>` tags. Could you add it to our main css and re-run gulp? :-) (Currently it's only inside our syncServerConnection branch.

See here: https://github.com/SStalker/EVOS/blob/1186d04c77cf0f933cad17144a3a5339c9528642/resources/views/questions/show.blade.php

**Comment by lhannigbrinck** [comment]
Am ende wird es für jeden bereich eine eigene CSS und JS datei geben, die mit gulp erstellt wird.
