### ISSUE TITLE
Correct answers don't need to be send to attendees

### ISSUE THREAD

**Issue by lhannigbrinck** [SStalker/EVOS#94]

**Comment by SStalker** [comment]
Falls das damit gemeint war, dann geht das ganz schnell...
![unbenannt](https://cloud.githubusercontent.com/assets/1316491/15687204/c312604c-2773-11e6-8000-15e4426af76e.png)

**Comment by apollo7321** [comment]
Ich hatte mich falsch ausgedrückt, meine Schuld. Ich meinte eigentlich, dass an das Frontend die eigentlichen Fragen gar nicht geschickt werden müssen, da sie ja sowieso nicht angezeigt werden.

**Comment by apollo7321** [comment]
https://github.com/SStalker/EVOS/commit/5cc255c38f215ba34edf1a4e33d2b63a02c0e1f9
